In [6]:
from dataset import ProcessedLigandPocketDataset
from pathlib import Path
from torch.utils.data import DataLoader
import torch

In [3]:
train_dataset = ProcessedLigandPocketDataset(
                Path('../01.data/full_h_single_separate/', 'test.npz'))

In [9]:
train_dataset.collate_fn

<function dataset.ProcessedLigandPocketDataset.collate_fn(batch)>

In [10]:
DataLoader(train_dataset, 20, shuffle=False,
                          num_workers=1,
                          collate_fn=train_dataset.collate_fn,
                          pin_memory=True)

In [34]:
i=0
for x in train_dataset:
    print(x)
    ll = x['lig_coords']
    pp = x['pocket_coords'] 
    lm = x['lig_mask']
    pm = x['pocket_mask']
    i+=1
    if i==1: break

{'names': 'BSD_ASPTE_1_130_0/2z3h_A_rec_1wn6_bst_lig_tt_docked_3_pocket10.pdb_BSD_ASPTE_1_130_0/2z3h_A_rec_1wn6_bst_lig_tt_docked_3.sdf', 'lig_coords': tensor([[-5.0604e-01, -2.1377e-01,  7.5313e-01],
        [-1.5580e+00, -5.0977e-01, -2.7487e-01],
        [-2.7950e+00, -9.8977e-01,  1.2711e-04],
        [-3.0320e+00, -1.2388e+00,  1.5481e+00],
        [-2.0600e+00, -5.0277e-01,  2.5181e+00],
        [-7.5304e-01, -8.1777e-01,  2.0411e+00],
        [ 8.8196e-01, -6.6377e-01,  4.2013e-01],
        [ 1.9430e+00,  3.2823e-01,  5.5613e-01],
        [ 1.7340e+00,  1.4822e+00,  9.1513e-01],
        [ 3.2640e+00, -7.2766e-02,  2.5413e-01],
        [ 3.5170e+00, -1.4438e+00, -1.7687e-01],
        [ 2.3640e+00, -2.4438e+00, -3.0087e-01],
        [ 1.1410e+00, -2.0138e+00, -4.8729e-03],
        [ 4.4690e+00, -2.0468e+00,  8.1813e-01],
        [ 4.1760e+00, -1.2808e+00, -1.4169e+00],
        [-2.6930e+00, -8.4577e-01,  4.9031e+00],
        [-7.8004e-01, -1.7228e+00,  4.1591e+00],
        [-1.959

In [17]:
from equivariant_diffusion.en_diffusion import EnVariationalDiffusion

In [19]:
import torch

In [22]:
ligand =  {'x': ([[ 1.7947,  2.9332, -0.5155],
        [ 1.1287,  1.8402, -1.1835],
        [ 0.6907,  3.5532,  0.3465],
        [ 0.9777,  4.9312,  0.6725],
        [-0.4483,  3.4882, -0.7165],
        [-0.0493,  4.4512, -1.7115],
        [-0.1993,  2.1002, -1.3365],
        [-1.0033,  1.0092, -0.8465],
        [-0.7203,  0.1542,  0.1615],
        [-1.4943, -0.8548,  0.2895],
        [-2.3513, -0.7068, -0.6835],
        [-3.3953, -1.4988, -1.0435],
        [-3.7603, -2.6058, -0.4585],
        [-4.1483, -1.1018, -2.0925],
        [-3.8293,  0.0602, -2.7515],
        [-2.8173,  0.8602, -2.4765],
        [-2.1243,  0.4272, -1.4295],
        [ 2.9907,  2.3282,  0.2135],
        [ 2.6117,  1.7212,  1.4295],
        [ 2.7737,  0.2782,  2.0205],
        [ 1.8327,  0.1912,  3.1665],
        [ 2.4827, -0.8618,  1.1325],
        [ 4.2887,  0.2492,  2.5805],
        [ 5.2847, -0.9778,  2.9225],
        [ 6.4077, -0.6238,  1.8395],
        [ 4.6667, -2.2928,  2.6775],
        [ 5.6317, -0.8598,  4.3545],
        [-3.7061, -0.9188, -2.0569],
        [-3.7201, -1.9568, -0.9639],
        [-2.7681, -2.6988, -0.7829],
        [-4.8111, -2.0558, -0.2169],
        [-4.7941, -2.9938,  0.8941],
        [-3.9481, -2.4438,  2.0401],
        [-6.1751, -3.2658,  1.3821],
        [-6.4351, -3.1458,  2.5801],
        [-7.0261, -3.5978,  0.5711],
        [-5.0971, -0.7608, -2.6889],
        [-5.4931, -1.9588, -3.8779],
        [-4.4151, -2.9968, -3.8779],
        [-5.7991, -1.2768, -5.1799],
        [-8.0071, -2.7118, -4.3489],
        [-6.8861, -2.8228, -3.3079],
        [-7.3641, -2.3358, -2.0209],
        [-3.2521,  0.4372, -1.4959],
        [-1.8821,  0.3502, -0.8849],
        [-1.7211,  0.4582,  0.4931],
        [-0.4561,  0.3602,  1.0631],
        [ 0.6709,  0.1462,  0.2591],
        [ 0.5009,  0.0422, -1.1259],
        [-0.7641,  0.1452, -1.6919],
        [ 2.0049,  0.0222,  0.8591],
        [ 2.5309,  1.0592,  1.6411],
        [ 3.7979,  0.9482,  2.2071],
        [ 4.5549, -0.2018,  2.0031],
        [ 4.0419, -1.2408,  1.2281],
        [ 2.7779, -1.1268,  0.6581],
        [ 2.2819,  0.3386,  1.6585],
        [ 2.6959, -1.0454,  1.5665],
        [ 2.5079,  0.9086,  0.2585],
        [ 3.8659,  1.3526,  0.1575],
        [ 2.2139, -0.2884, -0.6585],
        [ 3.0379, -0.2814, -1.8275],
        [ 2.5619, -1.5124,  0.1975],
        [ 1.5349, -2.5854,  0.2095],
        [ 0.2159, -2.4314,  0.0865],
        [-0.3841, -3.6154,  0.2045],
        [ 0.5539, -4.5294,  0.4535],
        [ 0.5129, -5.9074,  0.6855],
        [-0.5551, -6.5254,  0.6945],
        [ 1.7279, -6.5834,  0.8995],
        [ 2.9409, -5.8694,  0.8745],
        [ 4.0959, -6.5034,  1.0695],
        [ 2.9329, -4.5454,  0.6345],
        [ 1.7829, -3.8724,  0.4415],
        [ 0.8209,  0.4766,  2.1085],
        [-0.0231,  0.9846,  1.0665],
        [-1.5731,  1.2216,  1.4075],
        [-2.4221,  0.6196,  0.3585],
        [-1.7021,  0.7636,  2.8085],
        [-1.8271,  2.8316,  1.3995],
        [-1.6231,  3.8736,  0.1605],
        [-2.5081,  3.5356, -0.9815],
        [-1.7841,  5.2066,  0.7835],
        [ 0.1369,  3.6896, -0.2855],
        [ 0.7479,  4.9606, -1.4565],
        [ 0.2389,  4.3966, -2.8795],
        [ 0.3109,  6.3586, -1.2065],
        [ 2.3509,  4.8826, -1.5025],
        [ 1.6655, -1.3771,  0.5799],
        [-0.0735, -2.9981,  0.6449],
        [ 1.1725, -1.4681, -0.8681],
        [ 0.4455, -3.7091, -0.6091],
        [ 1.0005, -2.3611,  1.3719],
        [ 1.3515, -2.8151, -1.2821],
        [ 5.5603,  3.8133, -2.2732],
        [ 5.8393,  4.3493, -1.0222],
        [ 5.5593,  3.6463,  0.1498],
        [ 4.9933,  2.3753,  0.1428],
        [ 4.6703,  1.7603, -1.0582],
        [ 4.0713,  0.4053, -1.1282],
        [ 3.7763, -0.1407, -2.3772],
        [ 4.0483,  0.5553, -3.5522],
        [ 4.6133,  1.8283, -3.5302],
        [ 4.9403,  2.4603, -2.3352],
        [ 5.9003,  4.6943, -3.5692],
        [ 6.6063,  5.8503, -3.1102],
        [ 6.6633,  3.9533, -4.5352],
        [ 3.7543, -0.3247,  0.0228],
        [ 4.3433, -1.6327,  0.2558],
        [ 2.7613,  0.2003,  0.9528]], ),
        'one_hot': ([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])
}

In [9]:
from torch_scatter import scatter_add, scatter_mean 

In [2]:
import pickle
with open('lig.pickle', mode='br') as fi:
  lig = pickle.load(fi)
with open('po.pickle', mode='br') as fi:
  poc = pickle.load(fi)
with open('int.pickle', mode='br') as fi:
  int = pickle.load(fi)

In [3]:
with open('lig_n.pickle', mode='br') as fi:
  lig_n = pickle.load(fi)
with open('po_n.pickle', mode='br') as fi:
  poc_n = pickle.load(fi)
with open('int_n.pickle', mode='br') as fi:
  int_n = pickle.load(fi)

In [15]:
len(lig['x'])

110

In [14]:
lig['mask']

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], device='cuda:0')

In [16]:
xh0_lig = torch.cat([lig['x'], lig['one_hot']], dim=1)
xh0_pocket = torch.cat([poc['x'], poc['one_hot']], dim=1)
xh0_int = torch.cat([int['x'], int['one_hot']], dim=1)

In [13]:
lig['mask']

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], device='cuda:0')

In [17]:
mean = scatter_mean(xh0_lig[:, :3],lig['mask'], dim=0)

In [19]:
xh0_lig[:, :3]

tensor([[ 1.7947,  2.9332, -0.5155],
        [ 1.1287,  1.8402, -1.1835],
        [ 0.6907,  3.5532,  0.3465],
        [ 0.9777,  4.9312,  0.6725],
        [-0.4483,  3.4882, -0.7165],
        [-0.0493,  4.4512, -1.7115],
        [-0.1993,  2.1002, -1.3365],
        [-1.0033,  1.0092, -0.8465],
        [-0.7203,  0.1542,  0.1615],
        [-1.4943, -0.8548,  0.2895],
        [-2.3513, -0.7068, -0.6835],
        [-3.3953, -1.4988, -1.0435],
        [-3.7603, -2.6058, -0.4585],
        [-4.1483, -1.1018, -2.0925],
        [-3.8293,  0.0602, -2.7515],
        [-2.8173,  0.8602, -2.4765],
        [-2.1243,  0.4272, -1.4295],
        [ 2.9907,  2.3282,  0.2135],
        [ 2.6117,  1.7212,  1.4295],
        [ 2.7737,  0.2782,  2.0205],
        [ 1.8327,  0.1912,  3.1665],
        [ 2.4827, -0.8618,  1.1325],
        [ 4.2887,  0.2492,  2.5805],
        [ 5.2847, -0.9778,  2.9225],
        [ 6.4077, -0.6238,  1.8395],
        [ 4.6667, -2.2928,  2.6775],
        [ 5.6317, -0.8598,  4.3545],
 

In [18]:
xh0_lig[:, :3] = xh0_lig[:, :3] - mean[lig['mask']]

tensor([[ 0.6378,  0.6738,  0.2430],
        [-2.5394, -1.2601, -0.5738],
        [ 0.8021, -0.3029,  0.2933],
        [ 0.9270, -2.4548, -0.0271],
        [ 4.8813,  2.1122, -1.6854]], device='cuda:0')

In [22]:
int['mask']

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], device='cuda:0')

In [21]:
mean[int['mask']]

tensor([[ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [ 0.6378,  0.6738,  0.2430],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [-2.5394, -1.2601, -0.5738],
        [ 0.8021, -0.3029,  0.2933],
        [ 0.8021, -0.3029,  0.2933],
 